FROM python:3.8-slim

USER root
COPY . /build

WORKDIR /build

RUN apt update && apt install -y nodejs npm 
RUN npm i -g yarn

WORKDIR /build/backend-webrtc

RUN pip install -r requirements.txt

EXPOSE 8080
CMD ["python", "aiortcapp.py"]
